name: dot-cart

on:
  push:
    branches:
      - master
env:
  REDIS_CONFIG: "redis:6379"
  EVENTSTORE_URI: "esdb+discover://eventstore:2113?tls=false"
  EVENTSTORE_USER: "admin"
  EVENTSTORE_PWD: "changeit"
  NATS_URI: "nats://nats:4222"
  NATS_USR: "a"
  NATS_PWD: "a"

jobs:
  
  build:

    runs-on: ubuntu-latest
    environment: Production
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Make Scripts Executable
        run: chmod +x ./cid
      - name: Install dependencies
        run: dotnet restore
      - name: Build Packages
        run: dotnet build --configuration Release --no-restore
  #      - name: Test Packages
  #        run: dotnet test --no-restore --verbosity minimal
  #      - name: Build Packages
  #        run: ./cid/build.sh DotCart.root.sln
  #      - name: Test Packages
  #        run: ./cid/run_unit_tests.sh DotCart.root.sln
  #      - name: Publish Packages
  #        run: ./cid/pub_pkg.sh
  #        env:
  #          NUGET_API_KEY: ${{secrets.MACULA_NUGET_ORG_KEY}}
  #          NUGET_URL: https://api.nuget.org/v3/index.json
  #      - name: Test Published Packages
  #        run: ./cid/testpub.sh
  #        env:
  #          NUGET_API_KEY: ${{secrets.MACULA_NUGET_ORG_KEY}}
  #          NUGET_URL: https://api.nuget.org/v3/index.json

  test:

    runs-on: ubuntu-latest
    environment: Production
    container: mcr.microsoft.com/dotnet/sdk
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]


    services:
      
      eventstore:
        env:
          EVENTSTORE_CLUSTER_SIZE: "1"
          EVENTSTORE_RUN_PROJECTIONS: "All"
          EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
          EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
          EVENTSTORE_INSECURE: "true"
        image: eventstore/eventstore:21.10.6-buster-slim
        ports:
          - 2113:2113
        options: >-
          --health-cmd "curl -X GET -u admin:changeit http://localhost:2113/info" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

      nats:
        env:
          NATS_CLUSTER: "default"
          NATS_CLIENT: "default"
        image: nats:2.8.4-scratch
        ports:
          - 4222:4222
          - 6222:6222
          - 8222:8222
      
      redis:
        image: redis:7.0.4-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Make Scripts Executable
        run: chmod +x ./cid
      - name: Verify NATS connection
        run: ./cid/check_nats.sh nats
      - name: Install dependencies
        run: dotnet restore
      - name: Test Packages
        run: dotnet test --no-restore --verbosity minimal --logger trx --results-directory ./TST-RES
